[project]
name = "yfinance-app"
version = "0.0.1"
requires-python = ">= 3.12"
dependencies = [
    # Data handling
    "pandas",
    "python-dotenv",
    "yfinance",
    "ydata-profiling",
    "setuptools",
    "TA-Lib",
    "scikit-learn",
    "zipline-reloaded",

    # Jupyter
    "jupyter",
    "ipykernel",
    "tqdm",

    # AWS
    "sagemaker",
    "boto3",
    "awscli",

    # Config
    "pyyaml",

    # Deep learning and model training
    "torch",
    "joblib",
    "matplotlib",
]

[dependency-groups]
dev = [
    "pylint",
    "pytest",
    "mypy",
    "coverage",
]
